### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by gumgood** [gumgood/gumgood.github.io#3]
## Refactoring

- [ ] `jekyll-include-cache` 적용하기
- [ ] https://shopify.github.io/liquid/basics/whitespace/ 적용하기
- [ ] css `color`값들 variable 만들기
- [ ] css 안 쓰는 값들 지우기
- [ ] tag 디자인

## Feature

- [ ] 검색 페이지: 실시간 loading하고 있는데 query string으로 받아서 처리하게 변경
- [ ] Post: Table of content 지원
- [ ] Category별로도 post 보여주고 싶은데 - search script 활용해서 paginate 지원

## Posting

- [ ] (Python) *args로 int or tuple, unpack 하는 방법
- [ ] (Torch) cross entropy에 다차원 tensor를 넣을 때 동작
- [ ] (Torch) nn.CrossEntropy와 F.CrossEntropy 차이
- [ ] (Torch) Q. How to delete layer in pre-trained model, A. (torch community) 지울 layer을 indentity로 대체
- [ ] (Python) 2D max 찾는 법 max(max(a))하면 안 됨
- [ ] (Python) 이진수 출력 & 이진수 입력 - 포매팅 이용방법
- [ ] Mathjax scroll 시키기
- [ ] python 코드 실행 측정 - timeit
- [ ] 빠른 입출력 byte 스트링 주의하도록 업데이트
